--BIẾN
--1. Là 1 vùng nhớ trong bộ nhớ để lưu trữ dữ liệu
--2. Cú pháp
--	DECLARE  @tên_biến  kiểu_dữ_liệu
--	Ví dụ:
--	DECLARE @masv VARCHAR(10)
--3. Gán giá trị cho biến
--	SET @tên_biến = giá_trị
--	hoặc
--	SELECT @tên_biến = giá_trị