CREATE DATABASE QLDIEM
GO
USE QLDIEM
GO
--Tạo bảng Lop
CREATE TABLE Lop
(
	MaLop VARCHAR(10) PRIMARY KEY,
	TenLop NVARCHAR(20) NOT NULL,
	NamVaoHoc INT
)

--Tạo bảng SinhVien
GO
CREATE TABLE SinhVien
(
	MaSV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	NgaySinh DATETIME,
	GioiTinh NVARCHAR(3) CHECK (GioiTinh = 'Nam' OR GioiTinh = N'Nữ'),
	MaLop VARCHAR(10) FOREIGN KEY REFERENCES Lop(MaLop)
)

--Tạo bảng Mon
GO
CREATE TABLE Mon
(
	MaMon VARCHAR(10) PRIMARY KEY,
	TenMon NVARCHAR(20) UNIQUE,
	SoDVHT INT
)

--Tạo bảng Diem
GO
CREATE TABLE Diem
(
	MaSV VARCHAR(10) FOREIGN KEY REFERENCES SinhVien(MaSV),
	MaMon VARCHAR(10) FOREIGN KEY REFERENCES Mon(MaMon),
	DiemCC INT CHECK (DiemCC >= 0 AND DiemCC <=10),
	DiemKT INT CHECK (DiemKT >= 0 AND DiemKT <=10),
	DiemThi INT CHECK (DiemThi >= 0 AND DiemThi <=10),
	PRIMARY KEY (MaSV, MaMon)
)

