--Tạo database QLDA
CREATE DATABASE QuanLyDuAn
GO
USE QuanLyDuAn
GO
--Tạo bảng DonVi
CREATE TABLE DonVi
(
	MaDV VARCHAR(10) PRIMARY KEY,
	TenDV NVARCHAR(50) NOT NULL,
	MaTP VARCHAR(20),
	NgayBD DATETIME,
	SoNV INT
)
GO
--Tạo bảng NhanVien
CREATE TABLE NhanVien
(
	MaNV VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATETIME,
	GioiTinh NVARCHAR(5),
	HeSoLuong FLOAT,
	DiaChi NVARCHAR(100),
	MaDV VARCHAR(10) FOREIGN KEY REFERENCES DonVi(MaDV),
	NgayVL DATETIME
)
GO
--Tạo bảng DiaDiem_DonVi
CREATE TABLE DiaDiem_DonVi
(
	MaDV VARCHAR(10) FOREIGN KEY REFERENCES DonVi(MaDV),
	DiaDiem NVARCHAR(50),
	PRIMARY KEY (MaDV, DiaDiem)
)
GO
--Tạo bảng DuAn
CREATE TABLE DuAn
( 
	MaDA VARCHAR(10) PRIMARY KEY,
	TenDA NVARCHAR(100) NOT NULL,
	DiaDiem NVARCHAR(100),
	NgayBD DATETIME,
	MaDV VARCHAR(10) FOREIGN KEY REFERENCES DonVi(MaDV)
)
GO
--Tạo bảng ThanNhan
CREATE TABLE ThanNhan
(
	HoTen NVARCHAR(30) PRIMARY KEY,
	NgaySinh DATETIME,
	GioiTinh NVARCHAR(5),
	QuanHe NVARCHAR(10),
	MaNV VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(MaNV)
)
GO
--Tạo bảng PhanCong
CREATE TABLE PhanCong
(
	MaDA VARCHAR(10) FOREIGN KEY REFERENCES DuAn(MaDA),
	MaNV VARCHAR(10) FOREIGN KEY REFERENCES NhanVien(MaNV),
	SoGio INT,
	NgayLamDA DATETIME,
	PRIMARY KEY (MaDA, MaNV)
)
GO
--Bổ sung các ràng buộc
--Ràng buộc giới tính chỉ nhận "Nam" và "Nữ"
USE QuanLyDuAn
GO
ALTER TABLE NhanVien
ADD CONSTRAINT c_GioiTinh CHECK (GioiTinh ='Nam' OR GioiTinh=N'Nữ')

GO
ALTER TABLE ThanNhan
ADD CONSTRAINT c_GTThanNhan CHECK (GioiTinh ='Nam' OR GioiTinh=N'Nữ')

GO
ALTER TABLE ThanNhan
ADD CONSTRAINT c_QuanHe CHECK (QuanHe IN (N'Chồng',N'Vợ',N'Bố',N'Mẹ','Con'))

GO
ALTER TABLE PhanCong
ADD CONSTRAINT c_SoGio CHECK (SoGio>=2 AND SoGio<=10)

GO
ALTER TABLE NhanVien
ADD CONSTRAINT d_HSL DEFAULT (3) FOR HeSoLuong
